Track_local_data
================

Sphinx Website:

http://www.nefsc.noaa.gov/epd/ocean/MainPage/py/sphinx_track_local/_build/html/index.html

--"collection.py" can help us choose some drifts which meet conditions(floating time/start time)

--"comparedrift.py" plots a map to show the difference between model and observe drift data.

--'diskcircletrack.py' can get the concentric points tracks, you need run "getcirclepoint.py"first to get the concentric points, it will generate npython file "XY.npz"

--"distance.py" --"distance.py" seperates  drift tracks into two-days long period and generates a output file to record the mean distance/std and mean of mean/std for each part.

--"distance_different_windcoefficient.py" plots several tracks in same beginning point but with different wind stress coefficients.

--"distance_with_wind.py" plots drifter,modeled,modeled with wind stress track figure. Also creats the output file named "drift_data/Drift_list.csv" to record distance of obs-model and obs-model_with_wind.

--'distanceplot.py' reads in files which were generated by"distance.py" and then plots the distance figure,x-axis is day(2days) and y-axis is distance(km).

--"getcirclepoint.py" can get concentric points which will uesd by "diskcircletrack.py".

--"S1-S6.py" are Vitalii programs,can generate vector figures to compare drifter and model tracks.
